[project]
name = "class18"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.3",
    "pwdlib[bcrypt]>=0.3.0",
    "pyjwt>=2.11.0",
    "uvicorn[standard]>=0.40.0",
]
